### ISSUE TITLE
openapi spec errors while generating a client

### ISSUE THREAD

**Issue by arnoud-koolecontrols** [scm-manager/scm-openapi-plugin#9]
I am trying to generate a c# client from the openapi spec.
While doing I am getting stuck at some errors.

![image (1)](https://user-images.githubusercontent.com/16818953/110902742-a36ffd00-8306-11eb-85e4-1dacabeca08f.png)

The easiest way to reproduce is to load the spec in: [https://editor.swagger.io/](https://editor.swagger.io/)
```
Semantic error at paths./v2/config/jenkins.get.operationId
Operations must have unique operationIds.
Jump to line 5597

Semantic error at paths./v2/config/jenkins.put.operationId
Operations must have unique operationIds.
Jump to line 5622

Semantic error at components.securitySchemes.Basic Authentication
Component names can only contain the characters A-Z a-z 0-9 - . _
Jump to line 8032

Semantic error at components.securitySchemes.Bearer Token Authentication
Component names can only contain the characters A-Z a-z 0-9 - . _
Jump to line 8036

```

**Comment by pfeuffer** [comment]
Hi @arnoud-koolecontrols , we just stumbled upon this ticket again. Does this work for you now after the various fixes we've made? Thanks for your feedback!

**Comment by arnoud-koolecontrols** [comment]
Hi @pfeuffer,
I have updated to 2.20.0 which is using openApi plugin v1.0.2

**Comment by arnoud-koolecontrols** [comment]
@pfeuffer  if I create a client , with the generator option to not skip Form models, then I can generate the client and build the code.

Example:
java -jar ../Generator/openapi-generator-cli-current.jar generate --global-property skipFormModel=false -g csharp-netcore -i openapi.json -o output --config config/GeneratorConfig.json

Ploblem solved 👍

**Comment by pfeuffer** [comment]
Thanks for the update, @arnoud-koolecontrols ! We would love to hear from your project :-)
